models/Interiors.php
<?php
namespace app\models;

use app\modules\admin\models\InteriorsFurniture;
use app\modules\admin\models\InteriorsDecorations;
use app\modules\admin\models\InteriorsRenovations;

class Interiors extends BaseModel
{
    public function behaviors()
    {
        return [
            'image' => [
                'class' => 'rico\yii2images\behaviors\ImageBehave',
            ],
        ];
    }

    public static function label(){
        return 'Галерея интерьеров';
    }

    public function attributeLabels()
    {
        return [
            'name' => 'Имя',
            'description' => 'Описание',
            'discount_cost' => 'Цена по скидке',
            'total_cost' => 'Цена',
            'image' => 'Изображения',
            'square' => 'Общая площадь',
            'projects_cost' => 'Общая стоимость',
            'renovations_cost' => 'Цена ремонтных работ',
            'furniture_cost' => 'Цена с мебелью',
            'decorations_cost' => 'Цена отделочных материалов',
        ];
    }

    public static function tableName(){
        return '{{%interiors}}';
    }

    public function getFurniture()
    {
        return $this->hasMany(Furniture::className(), ['id' => 'furniture_id'])
        ->viaTable(InteriorsFurniture::tableName(), ['interior_id' => 'id']);
    }

    public function getDecorations()
    {
        return $this->hasMany(Decorations::className(), ['id' => 'decorations_id'])
        ->viaTable(InteriorsDecorations::tableName(), ['interior_id' => 'id']);
    }

    public function getRenovations(){
        return $this->hasMany(Renovations::className(), ['id' => 'renovations_id'])
        ->viaTable(InteriorsRenovations::tableName(), ['interior_id' => 'id']);
    }

    public function getAllRelated()
    {
        return array_merge($this->furniture, $this->decorations, $this->renovations);
    }

    public function getAmount()
    {
        return $this->projects_cost + $this->furniture_cost + $this->decorations_cost + $this->renovations_cost;
    }
}

controllers/InteriorsController.php
<?php

namespace app\controllers;

use Yii;
use app\components\BaseController;
use app\models\Interiors;

class InteriorsController extends BaseController{

    public function actionIndex($filter = []){
        $interiors = Interiors::find()->orderBy("id DESC, name ASC")->all();

        return $this->render('index', [
            'interiors' => $interiors,
        ]);
    }

    public function actionView($alias)
    {
        $item = Interiors::findByAlias($alias);

        if ($item) {
            return $this->render('view', [
                'item' => $item,
            ]);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }


    }

    public function actionFilter($min = 0, $max = 0)
    {
        if (Yii::$app->request->isAjax) {
            $matches = Interiors::find()->orderBy("id DESC, name ASC")->where(['>','total_cost', (int)$min]);

            if (!empty($max)) {
                $matches = $matches->andWhere(['<','total_cost', (int)$max]);
            }

            $matches = $matches->all();

            echo $this->renderPartial('_item', [
                'interiors' => $matches,
            ]);
        }
    }
}

views/interiors/_item.php
<?php foreach ($interiors as $item): ?>
    <article class="gallery-item">
        <div class="gallery-item--img">
            <a href="<?= $item->getImages()[0]->getUrl(); ?>" data-lightbox="roadtrip-1">
                <img src="<?= $item->getImages()[0]->getUrl() ?>"/>
            </a>
            <p><?= $item->total_cost; ?> тг</p>
            <a href="<?= Yii::$app->urlManager->createUrl(['interiors/view']); ?>" class="galery-cursor"></a>
        </div>
        <div class="gallery-item--title">
            <a href="<?= Yii::$app->urlManager->createUrl(['interiors/view' , 'alias' => $item->alias]); ?>">
                <?= $item->name; ?>
            </a>
            <div class="tags hidden">
                <a href="">Современный,</a>
                <a href="">Модернизм,</a>
                <a href="">Фьюжн</a>
            </div>
        </div>
    </article>
<?php endforeach; ?>

views/interiors/index.php
<?php
use kartik\slider\Slider;

$this->title = 'Галерея';
?>

<section class="page">
    <div class="container">
        <ul class="breadcrumbs">
            <li><a href="<?= Yii::$app->urlManager->createUrl(['site/index']); ?>">Главная</a></li>
            <li><a href="<?= Yii::$app->urlManager->createUrl(['interiors']); ?>">Галерея</a></li>
        </ul>
        <div class="row">
            <!-- Фильтр устроен формой здесь -->
            <form id = "filter" method="post">
                <label for="min\">От:</label>
                <input class = "range" type="number" name="min" value = "0">
                <label for="max">До:</label>
                <input class = "range" type="number" name="max" value = "0">
            </form>
        </div>
        <div class="row page--wrapper">
            <!-- Фильтр для десктопа -->
            <div class="col-lg-2 col-md-3 col-xs-12 page--wrapper-left mob hidden">
                <div class="page--filter">
                    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingMenuOne">
                                <a role="button" class="accordion-button collapsed-in" data-toggle="collapse"
                                   data-parent="#accordion" href="#collapseMenuOne" aria-expanded="true"
                                   aria-controls="collapseOne">
                                    Стиль
                                </a>
                            </div>
                            <div id="collapseMenuOne" class="panel-collapse collapse in" role="tabpanel"
                                 aria-labelledby="headingMenuOne">
                                <div class="panel-body">
                                    <div class="group">
                                        <input type="checkbox" class="radio" id="chekbox-1-sidebar" name="radio">
                                        <label for="chekbox-1-sidebar">Современный</label>
                                    </div>
                                    <div class="group">
                                        <input type="checkbox" class="radio" id="chekbox-2-sidebar" name="radio">
                                        <label for="chekbox-2-sidebar">Фьюжн</label>
                                    </div>
                                    <div class="group">
                                        <input type="checkbox" class="radio" id="chekbox-3-sidebar" name="radio">
                                        <label for="chekbox-3-sidebar">Модернизм</label>
                                    </div>
                                    <div class="group">
                                        <input type="checkbox" class="radio" id="chekbox-4-sidebar" name="radio">
                                        <label for="chekbox-4-sidebar">Классический</label>
                                    </div>
                                    <div class="group">
                                        <input type="checkbox" class="radio" id="chekbox-5-sidebar" name="radio">
                                        <label for="chekbox-5-sidebar">Восточный</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingMenuTwo">
                                <a role="button" class="accordion-button collapsed-in" data-toggle="collapse"
                                   data-parent="#accordion2" href="#collapseMenuTwo" aria-expanded="true"
                                   aria-controls="collapseMenuTwo">
                                    Цвет
                                </a>
                            </div>
                            <div id="collapseMenuTwo" class="panel-collapse collapse in" role="tabpanel"
                                 aria-labelledby="headingMenuTwo">
                                <div class="panel-body">
                                    <div class="group">
                                        <input type="checkbox" class="radio" id="chekbox-6-sidebar" name="radio">
                                        <label for="chekbox-6-sidebar">Светлый</label>
                                    </div>
                                    <div class="group">
                                        <input type="checkbox" class="radio" id="chekbox-7-sidebar" name="radio">
                                        <label for="chekbox-7-sidebar">Темный</label>
                                    </div>
                                    <div class="group">
                                        <input type="checkbox" class="radio" id="chekbox-8-sidebar" name="radio">
                                        <label for="chekbox-8-sidebar">Комбинированный</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingMenuThree">
                                <a role="button" class="accordion-button collapsed-in" data-toggle="collapse"
                                   data-parent="#accordion3" href="#collapseMenuThree" aria-expanded="true"
                                   aria-controls="collapseMenuThree">
                                    Бюджет
                                </a>
                            </div>
                            <div id="collapseMenuThree" class="panel-collapse collapse in" role="tabpanel"
                                 aria-labelledby="headingMenuThree">
                                <div class="panel-body">
                                    <div class="group">
                                        <input type="checkbox" class="radio" id="chekbox-9-sidebar" name="radio">
                                        <label for="chekbox-9-sidebar">Бюджетный</label>
                                    </div>
                                    <div class="group">
                                        <input type="checkbox" class="radio" id="chekbox-10-sidebar" name="radio">
                                        <label for="chekbox-10-sidebar">Средний</label>
                                    </div>
                                    <div class="group">
                                        <input type="checkbox" class="radio" id="chekbox-11-sidebar" name="radio">
                                        <label for="chekbox-11-sidebar">Люкс</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="page--filter-button">Применить</button>
                    </div>
                </div>
            </div>

            <!-- Следующий блок было col-lg-10 col-md-9 col-xs-12 -->
            <div class="col-lg-12 col-md-12 col-xs-12 page--wrapper-right">
                <div class="page--wrapper-right-title">
                    <h1>Галерея</h1>
                    <!-- <p>135 работ</p> -->
                </div>
                <div class="page--wrapper-right-description">
                    <!-- <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis accusamus architecto quam at
                        recusandae repellendus, asperiores delectus libero necessitatibus blanditiis, atque, tempore
                        minus aspernatur eaque cupiditate odio dolores quasi quae.
                    </p> -->
                </div>
                <div class="page--wrapper-right-items-gallery">
                    <?= $this->render('_item', [
                        'interiors' => $interiors,
                    ]); ?>
                </div>
                <ul class="pagination clearfix hidden">
                    <li><a class="active" href="">1</a></li>
                    <li><a href="">2</a></li>
                    <li><a href="">3</a></li>
                    <li><a href="">4</a></li>
                    <li><a href="">5</a></li>
                    <li><a href="">6</a></li>
                    <li><a href="">7</a></li>
                    <li><a href="">8</a></li>
                    <li><a href="">9</a></li>
                    <li><a href="">10</a></li>
                </ul>
            </div>
        </div>
    </div>
</section>

<!-- Простейший скрипт, который отправляет запрос на экшен -->
<?php $this->registerJs(sprintf(
    "$('.range').on('focusout', function(){
            let data = $('form#filter').serialize();

            $.get('%s?'+data, function(data){
                $('.page--wrapper-right-items-gallery').html('');
                $('.page--wrapper-right-items-gallery').append(data);
            })
    })", Yii::$app->urlManager->createUrl([Yii::$app->controller->id . '/filter'])
), yii\web\View::POS_READY); ?>

views/interiors/view.php
<?php

use yii\widgets\Breadcrumbs;

$this->title = 'Каталог';
?>
<section class="page">
    <div class="container">
        <ul class="breadcrumbs">
            <li><a href="/">Главная</a></li>
            <li><a href="<?= Yii::$app->urlManager->createUrl('interiors'); ?>">Галерея</a></li>
            <li><a><?= $item->name ?></a></li>
        </ul>
        <div class="row page--wrapper">
            <div class="col-lg-8 col-md-7 col-xs-12 page--wrapper-gallery-left">
                <div class="page--wrapper-gallery-left--slider">
                    <ul id="imageGallery">
                        <?php foreach ($item->getImages() as $image): ?>
                            <li data-thumb="<?= $image->getUrl('200x100'); ?>" data-src="<?= $image->getUrl('300x105'); ?>">
                                <img src="<?= $image->getUrl('300x100'); ?>" />
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <div class="page--wrapper-gallery-left--description">
                    <?= $item->description; ?>
                </div>
            </div>
            <div class="col-lg-4 col-md-5 col-xs-12 page--wrapper-gallery-right">
                <div class="page--wrapper-gallery-right--title">
                    <h1><?= $item->name; ?></h1>
                </div>
                <div class="page--wrapper-gallery-right--info">
                    <ul>
                        <li style="background: #f4f4f4; padding: 20px; margin-bottom: 18px;">
                            <p style="font-size: 22px;">Стоимость с мебелью и аксессуарами:</p>
                            <span style="font-size: 29px; font-weight: bold; color: #d51f2f;"><?= $item->total_cost; ?> тг/м2</span>
                        </li>

                        <li>
                            <p class="info-price">Площадь объекта:</p>
                            <span class="info-price"><?= $item->square; ?> m2</span>
                        </li>
                        <li>
                            <p class="info-price">Общая стоимость проекта:</p>
                            <span class="info-price"><?= $item->projects_cost; ?> тенге</span>
                        </li>
                        <li>
                            <p class="info-price">Стоимость ремонтных работ:</p>
                            <span class="info-price"><?= $item->renovations_cost; ?> тенге</span>
                        </li>
                        <li>
                            <p class="info-price">Стоимость отделочных материалов:</p>
                            <span class="info-price"><?= $item->decorations_cost; ?> тенге</span>
                        </li>
                        <li>
                            <p class="info-price">Стоимость мебели и аксессуаров:</p>
                            <span class="info-price"><?= $item->furniture_cost; ?> тенге</span>
                        </li>
                    </ul>
                </div>
                <div class="page--wrapper-gallery-right--price">
                    <h2>Спецификация</h2>
                    <div class="tabs">
                        <ul class="tabs__caption">
                            <li class="active">Общая стоимость</li>
                            <li>Мебель и аксессуары</li>
                            <li>Отделочные материалы</li>
                            <li>Ремонтные работы</li>
                        </ul>
                        <div class="tabs__content mCustomScrollbar active" data-mcs-theme="dark" >
                            <?php foreach ($item->allRelated as $related): ?>
                                <article class="tabs__content_items">
                                    <div class="tabs__content_item__left">
                                        <?php if ($image = $related->getImage()): ?>
                                            <div class="tabs__content_item__left_img">
                                                <img src="<?= $image->getUrl('50x50'); ?>" alt="">
                                            </div>
                                        <?php endif; ?>

                                        <div class="tabs__content_item__left_description">
                                            <p><?= $related->name; ?></p>
                                            <span><?= $related->description; ?></span>
                                        </div>
                                    </div>
                                    <div class="tabs__content_item__right_price">
                                        <?= $related->total_cost ?> тг
                                    </div>
                                </article>
                            <?php endforeach; ?>

                        </div>
                        <div class="tabs__content">
                            <?php foreach ($item->furniture as $furniture): ?>
                                <article class="tabs__content_items">
                                    <div class="tabs__content_item__left">
                                        <div class="tabs__content_item__left_img">
                                            <img class = "img-responsive" src=<?= $furniture->getImage()->getUrl("50x50"); ?> alt="">
                                        </div>
                                        <div class="tabs__content_item__left_description">
                                            <p><?= $furniture->name; ?></p>
                                            <span><?= $furniture->description; ?></span>
                                        </div>
                                    </div>
                                    <div class="tabs__content_item__right_price">
                                        <?= $furniture->total_cost; ?> тг
                                    </div>
                                </article>
                            <?php endforeach; ?>
                        </div>
                        <div class="tabs__content">
                            <?php foreach ($item->decorations as $decoration): ?>
                                <article class="tabs__content_items">
                                    <div class="tabs__content_item__left">
                                        <div class="tabs__content_item__left_img">
                                            <img src="<?= $decoration->getImage()->getUrl("50x50"); ?>" alt="">
                                        </div>
                                        <div class="tabs__content_item__left_description">
                                            <p><?= $decoration->name ?></p>
                                        </div>
                                    </div>
                                    <div class="tabs__content_item__right_price">
                                        <?= $decoration->total_cost; ?> тг
                                    </div>
                                </article>
                            <?php endforeach; ?>

                        </div>
                        <div class="tabs__content">
                            <?php foreach ($item->renovations as $renovation): ?>
                                <article class="tabs__content_items">
                                    <div class="tabs__content_item__left">
                                        <div class="tabs__content_item__left_description">
                                            <p><?= $renovation->name ?></p>
                                        </div>
                                    </div>
                                    <div class="tabs__content_item__right_price">
                                        <?= $renovation->total_cost; ?> тг
                                    </div>
                                </article>
                            <?php endforeach; ?>

                        </div>
                    </div>
                </div>

                <div class="page--wrapper-gallery-right--total">
                    <div class="right--total-price">
                        <p>Итого:</p>

                        <span><?= $item->amount; ?> тг</span>
                    </div>
                    <div class="right--total-button">
                        <button href="#call-consult" class="total-button--modal button-consult">Хочу так же</button>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 page--wrapper-gallery-more">
                <div class="page--wrapper-gallery-more--title">
                    <h3>Обратите внимание</h3>
                </div>
                <div class="page--wrapper-right-items-gallery">
                    <article class="gallery-item gallery-item-full-page">
                        <div class="gallery-item--img">
                            <a href="img/gallery/gl1.jpg" data-lightbox="roadtrip-8"><img src="img/gallery/gl1.jpg" /></a>
                            <p>65 000 тг/м2</p>
                            <a href="" class="galery-cursor"></a>
                        </div>
                        <div class="gallery-item--title">
                            <a href="">Дом с барельефами и витражами</a>
                            <div class="tags hidden">
                                <a href="">Современный,</a>
                                <a href="">Модернизм,</a>
                                <a href="">Фьюжн</a>
                            </div>
                        </div>
                    </article>
                    <article class="gallery-item gallery-item-full-page">
                        <div class="gallery-item--img">
                            <a href="img/gallery/gl1.jpg" data-lightbox="roadtrip-8"><img src="img/gallery/gl1.jpg" /></a>
                            <p>65 000 тг/м2</p>
                            <a href="" class="galery-cursor"></a>
                        </div>
                        <div class="gallery-item--title">
                            <a href="">Дом с барельефами и витражами</a>
                            <div class="tags hidden">
                                <a href="">Современный,</a>
                                <a href="">Модернизм,</a>
                                <a href="">Фьюжн</a>
                            </div>
                        </div>
                    </article>
                    <article class="gallery-item gallery-item-full-page">
                        <div class="gallery-item--img">
                            <a href="img/gallery/gl1.jpg" data-lightbox="roadtrip-8"><img src="img/gallery/gl1.jpg" /></a>
                            <p>65 000 тг/м2</p>
                            <a href="" class="galery-cursor"></a>
                        </div>
                        <div class="gallery-item--title">
                            <a href="">Дом с барельефами и витражами</a>
                            <div class="tags hidden">
                                <a href="">Современный,</a>
                                <a href="">Модернизм,</a>
                                <a href="">Фьюжн</a>
                            </div>
                        </div>
                    </article>
                </div>
            </div>
        </div>
    </div>
</section>