controllers/CatalogController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;

use app\modules\admin\models\Catalog;

class CatalogController extends Controller
{
    public $layout = 'catalog';
    
    /**
     * @inheritdoc
     */

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                // 'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => [
                            'index','view'
                        ],
                        'allow' => true,
                        // 'roles' => ['@'],
                    ],
                ],
            ],

        ];
    }


    public function actionIndex()
    {
        $catalog = Catalog::find()->all();

        return $this->render('index',[
            'catalog' => $catalog,
        ]);
    }

    public function actionView()
    {
        return $this->render('view');
    }

}

controllers/GalleryController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;

use app\modules\admin\models\Gallery;

class GalleryController extends Controller
{
    public $layout = 'gallery';

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                // 'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => [
                            'index','view'
                        ],
                        'allow' => true,
                        // 'roles' => ['@'],
                    ],
                ],
            ],

        ];
    }


    public function actionIndex()
    {
        $gallery = Gallery::find()->all();
        return $this->render('index',[
            'gallery' => $gallery
        ]);
    }

    public function actionView()
    {
        $item = Gallery::find()->where(['id'=>Yii::$app->getRequest()->getQueryParam('id')])->one();

        return $this->render('view', [
            'item' => $item,
        ]);
    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{

    public $layout = 'main';

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContacts()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contacts', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'О нас';
// $this->params['breadcrumbs'][] = $this->title;
?>

<section class="page">
	<div class="container">
		<ul class="breadcrumbs">
			<li><a href="/">Главная</a></li>
			<li><a href="/about.html">О нас</a></li>
		</ul>
		<div class="row page--wrapper">
			<div class="col-xs-12 page--wrapper-contact">
				<div class="page--wrapper-contact-title">
					<h1>О нас</h1>
					<p>
						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi aperiam, asperiores aspernatur 						beatae dolorem eligendi illo in iste laboriosam maiores odit quo reiciendis rerum totam voluptatum? 						Incidunt laboriosam laudantium voluptate!
					</p>
				</div>
				<div class="page--wrapper-about">
					<div class="page--wrapper-about-album">
						<img src="img/about.png" alt="">
					</div>
					<div class="page--wrapper-about-description">
						<div class="page--wrapper-about-description-title">
							<h2>Заголовок второго уровня</h2>
						</div>
						<div class="row page--wrapper-about-content">
							<div class="col-md-6">
								<p>
									Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae commodi dolorem id
									molestiae pariatur porro, tempora voluptas? Consequatur cum ea fuga libero rerum
									sapiente. Eum necessitatibus nemo porro recusandae veritatis. Lorem ipsum dolor sit
									amet, consectetur adipisicing elit. Deleniti eum fugiat labore laborum sunt
									suscipit, ullam voluptatibus? Ad alias amet commodi eum explicabo facere facilis,
									magnam molestias neque odit, rem.</p>
							</div>
							<div class="col-md-6">
								<p>
									Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid atque error esse
									expedita facilis fugit harum ipsum, magnam magni nam neque odit officia officiis,
									perspiciatis placeat quam quisquam quod rem. Lorem ipsum dolor sit amet, consectetur
									adipisicing elit. Adipisci alias consectetur consequuntur delectus dicta dolorum
									expedita facilis, in inventore laborum libero molestiae nam nihil porro quasi
									recusandae veniam? A, earum.
								</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

views/site/contacts.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
// $this->params['breadcrumbs'][] = $this->title;
?>
    <section class="page">
        <div class="container">
            <ul class="breadcrumbs">
                <li><a href="/">Главная</a></li>
                <li><a href="/contact.html">Контакты</a></li>
            </ul>
            <div class="row page--wrapper">
                <div class="col-xs-12 page--wrapper-contact">
                    <div class="page--wrapper-contact-title">
                        <h1>Контакты</h1>
                        <p>
                            По всем вопросам, связанным с работой компании и дополнительной информацией о товаре и                          услугах, обращайтесь по телефонам расположенным ниже, также вы можете
                            <a href="">написать нам.</a>
                        </p>
                    </div>
                    <div class="page--wrapper-contact-icons">
                        <div class="contact-items">
                            <i class="contact-phone"></i>
                            <div class="item-info">
                                <span>Телефон</span>
                                <p>8 800 123 45 67</p>
                            </div>
                        </div>
                        <div class="contact-items">
                            <i class="contact-mail"></i>
                            <div class="item-info">
                                <span>E-mail</span>
                                <a href="">sample@mail.ru</a>
                            </div>
                        </div>
                        <div class="contact-items">
                            <i class="contact-skype"></i>
                            <div class="item-info">
                                <span>Skype</span>
                                <p>sample-skype</p>
                            </div>
                        </div>
                        <div class="contact-items">
                            <i class="contact-adress"></i>
                            <div class="item-info">
                                <span>Адрес</span>
                                <p>г. Астана, ул. Ленина 22/3</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Главная страница';
?>


<section class="header" id="container-1">
    <div class="swiper-container">
        <!-- Additional required wrapper -->
        <div class="swiper-wrapper">
            <div class="swiper-slide" style="background-image:url('img/slider/sl1.jpg')"></div>
            <div class="swiper-slide" style="background-image:url('img/slider/sl2.jpg')"></div>
            <div class="swiper-slide" style="background-image:url('img/slider/sl1.jpg')"></div>
        </div>
        <div class="header--scroll">
            <i class="icon-scroll-bottom"></i>
            <p>Прокрутите вниз</p>
        </div>
    </div>
</section>

<section class="why" id="container-2">
    <div class="container">
        <div class="why--wrapper">
            <div class="why--wrapper-title">
                <h1>Почему мы</h1>
                <p>Мы даем полное понимание стоимости ремонта</p>
            </div>
            <div class="why--wrapper-items">
                <article class="item">
                    <div class="item--img">
                        <img src="img/coffe.png" alt="" class="img-responsive coffe">
                    </div>
                    <p>Готовые проекты</p>
                    <span>
                        Работая с нами, у вас нет необходимости
                        заказывать дизайн-проект.
                    </span>
                    <span>                      
                        Вы имеете возможность выбрать одно из
                        готовых решений.
                    </span>
                </article>
                <article class="item">
                    <div class="item--img">
                        <img src="img/furniture.png" alt="" class="img-responsive furniture">
                    </div>
                    <p>Материалы и мебель</p>
                    <span>
                        Наши дизайн-проекты идеально
                        сбалансированы по стоимости и качеству
                        подобранных материалов и мебели.​
                    </span>
                    <span>                      
                        Вам не потребуется посещать рынки и
                        магазины в поисках всего необходимого
                        для реализации проекта
                    </span>
                </article>
                <article class="item">
                    <div class="item--img">
                        <img src="img/building.png" alt="" class="img-responsive building">
                    </div>
                    <p>Ремонтные работы</p>
                    <span>
                        На Вашем объекте будут работать
                        сертифицированные мастера, 
                        специализирующееся на работе c 
                        материалами, используемые в наших
                        проетах.
                    </span>
                    <span>                      
                        Гарантия на работы составляет 2 года.
                    </span>
                </article>
            </div>
            <button href="#call-consult" class="button-consult">Заказать выезд консультанта</button>
        </div>
    </div>
</section>

<section class="info" id="container-3">
    <div class="container-fluid">
        <div class="col-md-6 col-sm-6 col-xs-12 info--catalog">
            <div class="info--catalog-wrapper">
                <div class="wrapper-title">
                    <p>Каталог</p>
                    <span>товаров</span>
                    <a href="<?= Yii::$app->urlManager->createUrl(['catalog/index']); ?>" class="go-catalog1">Перейти в каталог</a>
                </div>
            </div>
            <a href="<?= Yii::$app->urlManager->createUrl(['catalog/index']); ?>" class="ab-href1"></a>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-12 info--interior">
            <div class="info--catalog-wrapper right-wrapper">
                <div class="wrapper-title">
                    <p>Галерея</p>
                    <span>интерьеров</span>
                    <a href="<?= Yii::$app->urlManager->createUrl(['gallery/index']); ?>" class="go-catalog2">Перейти в галерею</a>
                </div>
            </div>
            <a href="<?= Yii::$app->urlManager->createUrl(['gallery/index']); ?>" class="ab-href2"></a>
        </div>
    </div>
</section>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>