models/Products.php
<?php
namespace app\models;

use app\models\BaseModel;

class Products extends BaseModel
{
    public function behaviors()
    {
        return [
            'image' => [
                'class' => 'rico\yii2images\behaviors\ImageBehave',
            ],
        ];
    }

    public static function label(){
        return 'Каталог товаров';
    }

    public function attributeLabels()
    {
        return [
            'name' => 'Имя',
            'available' => 'Есть в наличии',
            'description' => 'Описание',
            'discount_cost' => 'Цена по скидке',
            'total_cost' => 'Цена',
            'image' => 'Изображения',
            'article' => 'Артикул',
            'style_type' => 'Стиль',
            'size' => 'Габариты',
        ];
    }

    public static function tableName(){
        return '{{%products}}';
    }

    public function getCategory(){
        return $this->hasOne(Categories::className(), ['id' => 'category_id']);
    }
}

controllers/ProductsController.php
<?php

namespace app\controllers;

use Yii;
use app\components\BaseController;
use app\models\Products;

class ProductsController extends BaseController
{
    public function actionIndex($categoryName = false){
        $products = Products::find()->all();

        return $this->render('index',[
            'products' => $products,
        ]);
    }

    public function actionView($alias)
    {
        $item = Products::findByAlias($alias);

        return $this->render('view', [
            'item' => $item,
        ]);
    }
}

views/products/index.php
<?php

/* @var $this yii\web\View */

$this->title = "Каталог";
?>

<section class="page">
    <div class="container">
        <ul class="breadcrumbs">
            <li><a href="/">Главная</a></li>
            <li><a href="/catalog.html">Каталог</a></li>
        </ul>
        <div class="row page--wrapper">
            <div class="col-lg-2 col-md-3 col-xs-12 page--wrapper-left hidden">
                <div class="page--wrapper-left--category">
                    <div class="category--title">Категори</div>
                    <ul class="category--wrapper">
                        <li>
                            <img src="/img/category-icon/icon1.png"  alt="">
                            <a href=""></a>
                            <p>Внутренняя отделка стен</p>
                        </li>
                        <li>
                            <img src="/img/category-icon/icon2.png"  alt="">
                            <a href=""></a>
                            <p>Напольные покрытия</p>
                        </li>
                        <li>
                            <img src="/img/category-icon/icon3.png"  alt="">
                            <a href=""></a>
                            <p>Для ванной</p>
                        </li>
                        <li>
                            <img src="/img/category-icon/icon4.png"  alt="">
                            <a href=""></a>
                            <p>Для гостиной</p>
                        </li>
                        <li>
                            <img src="/img/category-icon/icon5.png"  alt="">
                            <a href=""></a>
                            <p>Для спальни</p>
                        </li>
                        <li>
                            <img src="/img/category-icon/icon6.png"  alt="">
                            <a href=""></a>
                            <p>Для столов</p>
                        </li>
                        <li>
                            <img src="/img/category-icon/icon7.png"  alt="">
                            <a href=""></a>
                            <p>Для офиса</p>
                        </li>
                        <li>
                            <img src="/img/category-icon/icon8.png"  alt="">
                            <a href=""></a>
                            <p>Для детской</p>
                        </li>
                        <li>
                            <img src="/img/category-icon/icon9.png"  alt="">
                            <a href=""></a>
                            <p>Для кухни</p>
                        </li>
                        <li>
                            <img src="/img/category-icon/icon10.png" alt="">
                            <a href=""></a>
                            <p>Свет</p>
                        </li>
                        <li>
                            <img src="/img/category-icon/icon11.png" alt="">
                            <a href=""></a>
                            <p>Двери</p>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- Было: col-lg-10 col-md-9 col-xs-12 -->
            <div class="col-lg-12 col-md-12 col-xs-12 page--wrapper-right">
                <div class="page--wrapper-right-title">
                    <h1>Каталог</h1>
                </div>
                <div class="page--wrapper-right-description">

                </div>
                <div class="page--wrapper-right-items-catalog">
                    <?php foreach ($products as $item): ?>
                    <article class="catalog-item">
                        <div class="catalog-item--left">
                            <div class="flexslider c_slider">
                                <ul class="slides">
                                    <?php foreach ($item->getImages() as $image): ?>
                                        <li>
                                            <a href="<?= $image->getUrl(); ?>" data-lightbox="roadtrip" class="zoom-photo">
                                                <img src="<?= $image->getUrl(); ?>" />
                                            </a>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        </div>
                        <div class="catalog-item--right">
                            <a href="<?= Yii::$app->urlManager->createUrl(['products/view', 'alias' => $item->alias]); ?>"><?= $item->name; ?></a>
                            <div class="tags hidden">
                                <a href="">Совремeнный,</a>
                                <a href="">Модернизм,</a>
                                <a href="">Фьюжн</a>
                            </div>
                            <span class="price"><?= $item->total_cost; ?> тенге</span>
                            <div class="flexslider c_carousel">
                                <ul class="slides">
                                    <li>
                                        <img src="/img/divan.jpg" />
                                    </li>
                                    <li>
                                        <img src="/img/divan.jpg" />
                                    </li>
                                    <li>
                                        <img src="/img/divan.jpg" />
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </article>
                    <?php endforeach; ?>
                </div>

                <ul class="pagination clearfix hidden">
                    <li><a class="active" href="">1</a></li>
                    <li><a href="">2</a></li>
                    <li><a href="">3</a></li>
                    <li><a href="">4</a></li>
                    <li><a href="">5</a></li>
                    <li><a href="">6</a></li>
                    <li><a href="">7</a></li>
                    <li><a href="">8</a></li>
                    <li><a href="">9</a></li>
                    <li><a href="">10</a></li>
                </ul>
            </div>
        </div>
    </div>
</section>

views/products/view.php
<?php

/* @var $this yii\web\View */

$this->title = 'Каталог';
?>

<section class="page">
    <div class="container">
        <ul class="breadcrumbs">
            <li><a href="/">Главная</a></li>
            <li><a href="/catalog.html">Каталог</a></li>
            <li><a href="/catalog-item.html">Название товара</a></li>
        </ul>
        <div class="row page--wrapper">
            <div class="col-md-6 col-xs-12 page--wrapper-gallery-left">
                <div class="page--wrapper-gallery-left--slider">
                    <ul id="imageGallery">
                        <?php foreach ($item->getImages() as $image): ?>
                            <li data-thumb="<?= $image->getUrl(); ?>" data-src="<?= $image->getUrl(); ?>">
                                <img src="<?= $image->getUrl(); ?>" />
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
            <div class="col-md-6 col-xs-12 page--wrapper-catalog-right">
                <div class="page--wrapper-catalog-right--title">
                    <h1><?= $item->name ?></h1>
                </div>
                <div class="page--wrapper-catalog-right--info">
                    <ul>
                        <li>
                            <p>Наличие:</p>
                            <span><?= $item->available ? 'Есть в наличии' : 'Нет в наличии'; ?></span>
                        </li>
                        <li>
                            <p>Код товара:</p>
                            <span><?= $item->article; ?></span>
                        </li>
                        <li>
                            <p>Стиль:</p>
                            <span><?= $item->style_type ?></span>
                        </li>
                        <li>
                            <p>Габариты:</p>
                            <span><?= $item->size; ?></span>
                        </li>
                    </ul>
                </div>
                <div class="page--wrapper-catalog-right--price">
                    <div class="page--wrapper-catalog-right--price-total">
                        <span><?= $item->discount_cost; ?> тг</span>
                        <p><?= $item->total_cost ?> тг</p>
                    </div>
                    <div class="page--wrapper-catalog-right--price-buy">
                        <div class="input-number-box">
                            <input type="text" min="1" class="input-number" value="1">
                            <div class="btn input-number-more"></div>
                            <div class="btn input-number-less"></div>
                        </div>
                        <button href="#buy-modal" class="buy_btn">Купить</button>
                    </div>
                </div>
                <div class="page--wrapper-catalog-right--description">
                    <p><?= $item->description; ?></p>
                </div>
                <div class="page--wrapper-catalog-right--social">
                    <p>Поделиться</p>
                    <script src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js"></script>
                    <script src="//yastatic.net/share2/share.js"></script>
                    <div class="ya-share2" data-services="collections,vkontakte,facebook,odnoklassniki,moimir,gplus" data-counter=""></div>
                </div>
            </div>
            <div class="col-xs-12 page--wrapper-gallery-more">
                <div class="page--wrapper-gallery-more--title">
                    <h3>Обратите внимание</h3>
                </div>
                <div class="page--wrapper-right-items-catalog">
                    <article class="catalog-item">
                        <div class="catalog-item--left">
                            <div class="flexslider c_slider">
                                <ul class="slides">
                                    <li>
                                        <a href="img/divan.jpg" data-lightbox="roadtrip" class="zoom-photo"><img
                                                src="img/divan.jpg"/></a>
                                    </li>
                                    <li>
                                        <a href="img/divan.jpg" data-lightbox="roadtrip"><img src="img/divan.jpg"/></a>
                                    </li>
                                    <li>
                                        <a href="img/divan.jpg" data-lightbox="roadtrip"><img src="img/divan.jpg"/></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="catalog-item--right">
                            <a href="/catalog-item.html">Дом с барельефами и витражами</a>
                            <div class="tags">
                                <a href="">Совремeнный,</a>
                                <a href="">Модернизм,</a>
                                <a href="">Фьюжн</a>
                            </div>
                            <span class="price">65 000 тенге</span>
                            <div class="flexslider c_carousel">
                                <ul class="slides">
                                    <li>
                                        <img src="img/divan.jpg"/>
                                    </li>
                                    <li>
                                        <img src="img/divan.jpg"/>
                                    </li>
                                    <li>
                                        <img src="img/divan.jpg"/>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </article>
                    <article class="catalog-item">
                        <div class="catalog-item--left">
                            <div class="flexslider c_slider">
                                <ul class="slides">
                                    <li>
                                        <a href="img/divan.jpg" data-lightbox="roadtrip"><img src="img/divan.jpg"/></a>
                                    </li>
                                    <li>
                                        <a href="img/divan.jpg" data-lightbox="roadtrip"><img src="img/divan.jpg"/></a>
                                    </li>
                                    <li>
                                        <a href="img/divan.jpg" data-lightbox="roadtrip"><img src="img/divan.jpg"/></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="catalog-item--right">
                            <a href="/catalog-item.html">Дом с барельефами и витражами</a>
                            <div class="tags">
                                <a href="">Современный,</a>
                                <a href="">Модернизм,</a>
                                <a href="">Фьюжн</a>
                            </div>
                            <span class="price">65 000 тенге</span>
                            <div class="flexslider c_carousel">
                                <ul class="slides">
                                    <li>
                                        <img src="img/divan.jpg"/>
                                    </li>
                                    <li>
                                        <img src="img/divan.jpg"/>
                                    </li>
                                    <li>
                                        <img src="img/divan.jpg"/>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </article>
                </div>
            </div>
        </div>
    </div>
</section>